organization: kowaltz
repository: infrastructure
tf-version: 1.7.1

environments:
  - dev
  - prod

aws-region: eu-west-3  # Paris

aws-organizational-units:
  sharedinfra:
    environments: all
    aws-accounts:
      - name: network
        managed-policies: []
        dependencies:
          - name: root-aws_organization
            variables: []
      - name: database
        managed-policies: []
        dependencies:
          - name: env-aws_sharedinfra_network
            variables:
              - subnet_ids
        subnet:
          cidr: "10.0.2.0/24"
          security-groups:
            - name: egress
              allow-ingress: false
  workloads:
    environments: all
    aws-accounts:
      - name: marketplace
        managed-policies: []
        dependencies:
          - name: env-aws_sharedinfra_network
            variables:
              - subnet_ids
          - name: env-aws_sharedinfra_database
            variables: []
        subnet:
          cidr: "10.0.3.0/24"
          security-groups:
            - name: public
              allow-ingress: true
            - name: egress
              allow-ingress: false
  sandbox:
    environments: dev
    aws-accounts:
      - name: sandbox
        managed-policies: []
        dependencies: []
