# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

# Controls when the action will run.
on:
  workflow_call:

# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  getSpacectlCredentials:
    uses: ${{ github.repository_owner }}/infrastructure/.github/workflows/♻get_spacectl_credentials.yml
  
  buildAndPushToAWS:
    uses: ${{ github.repository_owner }}/infrastructure/.github/workflows/♻build_and_push_to_aws.yml
