# This is a basic workflow to help you get started with Actions
name: Connect to Spacelift, build AMI, and push it to AWS

# Controls when the action will run.
on:
  workflow_dispatch:

# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  getSpacectlCredentials:
    uses: ./.github/workflows/♻get_spacectl_credentials.yml
  
  buildAndPushToAWS:
    needs: getSpacectlCredentials
    uses: ./.github/workflows/♻build_and_push_to_aws.yml
    with:
      AWS_ACCOUNT_ID_INFRASTRUCTURE_ENV_VMS: ${{ needs.getSpacectlCredentials.outputs.AWS_ACCOUNT_ID_INFRASTRUCTURE_ENV_VMS }}
