name: Build VM images
on:
  push:
    branches: [ dev, prod ]
    paths: [
      ".github/workflows/build_vm_images.yml",
      ".github/workflows/test_connection_aws.yml",
      "vms/*"
    ]
  workflow_dispatch:

jobs:
  test-connection:
    uses: ./.github/workflows/test_connection_aws.yml

  build:
    needs: test-connection
    uses: ./.github/workflows/packer.yml
