# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

# Controls when the action will run.
on:
  workflow_call:
    secrets:
      SPACELIFT_API_KEY_ENDPOINT:
        required: true
      SPACELIFT_API_KEY_ID:
        required: true
      SPACELIFT_API_KEY_SECRET:
        required: true
    outputs:
      AWS_ACCOUNT_ID_INFRASTRUCTURE_ENV_VMS:
        value: ${{ jobs.get-aws-info.outputs.AWS_ACCOUNT_ID_INFRASTRUCTURE_ENV_VMS }}

# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  get-aws-info:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      SPACELIFT_API_KEY_ENDPOINT: ${{ secrets.SPACELIFT_API_KEY_ENDPOINT }}
      SPACELIFT_API_KEY_ID: ${{ secrets.SPACELIFT_API_KEY_ID }}
      SPACELIFT_API_KEY_SECRET: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
    outputs:
      AWS_ACCOUNT_ID_INFRASTRUCTURE_ENV_VMS: ${{ steps.test.outputs.AWS_ACCOUNT_ID_INFRASTRUCTURE_ENV_VMS }}
    steps:
      - id: install
        name: Install spacectl
        uses: spacelift-io/setup-spacectl@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - id: test
        name: Test connection
        run: |
          echo $SPACELIFT_API_KEY_ENDPOINT
          spacectl stack dependencies on --id=kowaltz-stack-dev-spacelift -o=json